### ISSUE TITLE
Add google colab tutorial to README

### ISSUE THREAD

**Issue by lucidBrot** [hucvl/attribute_hallucination#8]
Hi and thanks for hosting the code publicly!

I had no suitable machine around so I tried to run your GUI on colab... and succeeded.

If you'd like, feel free to add a section about how to do this based on [my colab jupyter file](https://colab.research.google.com/drive/1HRPMVR6T377TZ1VtZd0dO_j5G2w-twp1?usp=sharing). There were a few hurdles such as using the correct versions of the dependencies and forwarding the X-Server so that the GUI can be used. That all works now!

**Comment by aykuterdem** [comment]
Thank you Eric. We have added your notebook to our project website.
